version: "3.7"
services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    hostname: backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  postgres:
    image: postgres:13.6-alpine3.15
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env

volumes: 
  postgres_data: 
